name: "robot-tests"
description: "runs robot tests"
inputs:
  processes:
    description: 'The number of parallel processes to run'
    required: false
  storybook-url:
    description: 'The url where storybook is deployed'
    required: true
    default: "http://localhost:9002"
  browser:
    description: "The browser which will execute robot tests"
    required: true
    default: "chrome"
  includes:
    description: "The inclusions of the robot tests"
    required: false
  excludes:
    description: "The exclusions of the robot tests"
    required: false
  output-dir:
    description: "The location where the report will be placed"
    required: true
    default: "reports"
  path:
    description: "The path of the tests to execute"
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'
