name: Pull Request
on:
  pull_request:
    branches:
      - master
    types: [closed]

env:
  APPLICATION_PUBLISH_REPO: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
  APPLICATION_PUBLISH_BRANCH: master
  APPLICATION_PUBLISH_FOLDER: app/pr-${{ github.event.number }}
  APPLICATION_PUBLISH_MESSAGE: "docs: remove PR ${{ github.repository }}#${{ github.event.number }}"

jobs:
  CleanupDeployment:
    name: Cleanup Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.APPLICATION_PUBLISH_REPO }}
          ref: ${{ env.APPLICATION_PUBLISH_BRANCH }}
          ssh-key: ${{ secrets.ORG_GHPAGES_DEPLOY_KEY }}
          path: gh-docs
          fetch-depth: 0

      - name: Commit removal
        run: |
          cd ${{ github.workspace }}/gh-docs
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git rm -r ${APPLICATION_PUBLISH_FOLDER}
          git commit -m "${APPLICATION_PUBLISH_MESSAGE}"
          git push

      - name: Cleanup Folder
        if: always()
        run: |
          rm -rf ${{ github.workspace }}/gh-docs

      - name: mark environment as deactivated
        uses: bobheadxi/deployments@v0.4.3
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{env.APPLICATION_PUBLISH_FOLDER}}
          desc: Deployment was pruned
