name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  RESOLVE_REGISTRY: https://repo.orl.eng.hitachivantara.com/artifactory/api/npm/npm/
  APPLICATION_PUBLISH_REPO: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
  APPLICATION_PUBLISH_BRANCH: master
  APPLICATION_PUBLISH_FOLDER: app/pr-${{ github.event.number }}
  APPLICATION_PUBLISH_MESSAGE: "docs: application for PR ${{ github.repository }}#${{ github.event.number }}"
  APPLICATION_URL: https://${{ github.repository_owner }}.github.io/app/pr-${{ github.event.number }}/
  PR_URL: "Adoption Application published: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}"

jobs:
  Cypress-run-unix: 
    name: Cypress cross browser test unix
    runs-on: ubuntu-18.04
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: -u 2501 
    strategy:
      fail-fast: false 
      matrix:
        browser: [firefox, chrome]
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npx cypress info
          working-directory: ./
          record: true
          parallel: true
          browser: ${{matrix.browser}}

