name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  RESOLVE_REGISTRY: https://repo.orl.eng.hitachivantara.com/artifactory/api/npm/npm/
  APPLICATION_PUBLISH_REPO: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
  APPLICATION_PUBLISH_BRANCH: master
  APPLICATION_PUBLISH_FOLDER: app/pr-${{ github.event.number }}
  APPLICATION_PUBLISH_MESSAGE: "docs: application for PR ${{ github.repository }}#${{ github.event.number }}"
  APPLICATION_URL: https://${{ github.repository_owner }}.github.io/app/pr-${{ github.event.number }}/
  PR_URL: "Adoption Application published: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}"

jobs:
  Test:
    name: Lint, Jest
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  Build-Application:
    name: Build Application
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci    
          
      - name: Generate Application
        run: |
          npm run build

      - name: Archive Application
        uses: actions/upload-artifact@v1
        with:
          name: application
          path: ${{ github.workspace }}/build

      - name: Clean Folders
        if: always()
        run: |
          rm -rf ${{ github.workspace }}/build


  Cypress-run-unix: 
    name: Cypress cross browser test unix
    needs: [Build-Application]
    runs-on: ubuntu-18.04

    services:
      application:
        image: nginx
        volumes:
          - ${{ github.workspace }}/dist:/usr/share/nginx/html
        options: >-
          --name application

    strategy:
      fail-fast: false 
      matrix:
        browser: [chrome]
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Fetch Application
        uses: actions/download-artifact@v1
        with:
          name: application
          path: ${{ github.workspace }}/dist

      - name: Restart nginx
        uses: docker://docker
        with:
          args: docker restart application
          
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./
          browser: ${{matrix.browser}}
          wait-on: http://application
        env:
          CYPRESS_BASE_URL: http://application

